services:
    kunstmaan_menu.menu.adaptor:
        class: Kunstmaan\MenuBundle\Service\MenuAdaptor
        arguments: ['%kunstmaan_menu.menus%']
        tags:
            - { name: kunstmaan_admin.menu.adaptor }


    kunstmaan_menu.menu.service:
        class: Kunstmaan\MenuBundle\Service\MenuService
        arguments:
            - '%kunstmaan_menu.menus%'
            - '@kunstmaan_admin.domain_configuration'
            - '@doctrine.orm.entity_manager'
            - '%kunstmaan_menu.entity.menu.class%'
        public: true

    kunstmaan_menu.menu.render_service:
        class: Kunstmaan\MenuBundle\Service\RenderService
        arguments:
            - '@router'

    kunstmaan_menu.menu.repository:
        class: Kunstmaan\MenuBundle\Repository\MenuItemRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['%kunstmaan_menu.entity.menuitem.class%']

    kunstmaan_menu.menu.twig.extension:
        class: Kunstmaan\MenuBundle\Twig\MenuTwigExtension
        arguments:
            - '@kunstmaan_menu.menu.repository'
            - '@kunstmaan_menu.menu.render_service'
        tags:
            - { name: twig.extension }

    Kunstmaan\MenuBundle\Controller\MenuAdminListController:
        arguments: ['@kunstmaan_menu.menu.service']
        calls:
            - setContainer: [ ] # Container service locator will be injected filled by the services from subscribed services
        tags: [ 'controller.service_arguments', 'container.service_subscriber' ]

    Kunstmaan\MenuBundle\Controller\MenuItemAdminListController:
        arguments: [ '@kunstmaan_admin.domain_configuration', '@doctrine.orm.entity_manager' ]
        calls:
            - setContainer: [ ] # Container service locator will be injected filled by the services from subscribed services
        tags: [ 'controller.service_arguments', 'container.service_subscriber' ]
